import Link from 'next/link';
import { routes } from '@/lib/site';
import { example, faqs } from '@/data/content';

export function ContentSections() {
  return <>
    <section className="section grid gap-8 md:grid-cols-2 mobile-stack"><div><h2 className="font-display text-4xl">The hard part is not just writing the email. It is knowing how firm to be.</h2><p className="mt-5 muted">Freelancers often do not need a full invoicing system or collections workflow. They need to handle one uncomfortable moment well: the client has not paid, you need to follow up, and the client relationship still matters.</p></div><ul className="grid gap-3">{['A 5-day overdue invoice should not sound like a final notice.','A 30-day overdue invoice with no previous reminder may still need a firm first follow-up.','Professional wording should be the baseline, while the reminder stage should follow the situation.','Final Notice should depend on both overdue days and previous reminders.'].map(x=><li className="paper-card p-4" key={x}>✓ {x}</li>)}</ul></section>
    <section className="section !pt-0"><h2 className="font-display text-4xl">Get the next reminder right before you send it.</h2><div className="mt-8 grid gap-4 md:grid-cols-4 mobile-stack">{[['Know which reminder stage fits','FreelancerReply recommends Due Soon, Gentle Reminder, Firm Reminder, or Final Notice based on the situation you enter.'],['Understand the recommendation','Each draft includes a short reason explaining why that stage fits your overdue days, reminder history, and client relationship.'],['Send one focused draft','Instead of giving you Gentle, Firm, and Final all at once, FreelancerReply generates the reminder that best fits the current situation.'],['Adjust without starting over','Use “Make it softer” or “Make it firmer” to tune the draft while keeping the payment ask clear and professional.']].map(([a,b])=><div className="paper-card p-5" key={a}><h3 className="font-display text-2xl">{a}</h3><p className="mt-3 text-sm muted">{b}</p></div>)}</div></section>
    <section className="section grid gap-10 md:grid-cols-2 mobile-stack"><div><p className="label">How it works</p><h2 className="mt-3 font-display text-4xl">Describe the situation. Get the right reminder.</h2></div><ol className="grid gap-4">{['Enter the client name, invoice amount, days overdue, project or service, and how many reminders you have already sent.','FreelancerReply recommends the current reminder stage and explains why it fits.','Review the subject line, email body, and short DM. Check the invoice details and client context.','Copy the draft, make any edits you need, and send it from your own inbox or messaging tool.'].map((x,i)=><li className="paper-card p-5" key={x}><span className="label">Step {i+1}</span><p className="mt-2 muted">{x}</p></li>)}</ol></section>
    <section id="example" className="section !pt-0 scroll-mt-24"><div className="paper-card grid gap-8 p-6 md:grid-cols-[.8fr_1.2fr] mobile-stack"><div><p className="label">Example recommended reminder</p><h2 className="mt-3 font-display text-4xl">This example shows how FreelancerReply recommends a stage before drafting the email.</h2><dl className="mt-5 grid gap-2 text-sm muted">{Object.entries({Client:example.clientName,Amount:example.amount,'Days overdue':example.daysOverdue,Project:example.projectType,'Previous reminders':example.previousReminders,Relationship:example.clientRelationship}).map(([k,v])=><div className="flex justify-between gap-4 border-b border-[var(--border)] py-2" key={k}><dt>{k}</dt><dd className="font-semibold text-[var(--ink)]">{v}</dd></div>)}</dl></div><div><div className="rounded-xl border border-[var(--border)] bg-[var(--primary-soft)] p-4"><p className="label">Recommended stage</p><p className="mt-2 font-display text-3xl">{example.recommendedStage}</p><p className="mt-2 text-sm muted">{example.stageReason}</p></div><pre className="mt-5 whitespace-pre-wrap rounded-xl bg-[var(--paper)] p-4 text-sm leading-6"><strong>Subject: {example.subject}</strong>{`\n\n${example.body}\n\nShort DM:\n${example.dm}`}</pre></div></div></section>
    <section className="section !pt-0"><div className="grid gap-4 md:grid-cols-3 mobile-stack">{[['First Reminder','The invoice is a few days overdue, and you do not want to sound annoyed.'],['Clear Follow-Up','The invoice is clearly overdue, but you have only followed up once or not at all.'],['Final Notice Candidate','The invoice is significantly overdue, and you have already sent multiple reminders.'],['Long-Term Client','A reliable long-term client is late, and you do not want to damage the relationship.'],['Need the Next Follow-Up','Draft the current reminder now. Full reminder sequences are planned for future Pro workflow tools.'],['Copy and send yourself','Nothing is sent automatically. You stay in control.']].map(([a,b])=><div className="paper-card p-5" key={a}><h3 className="font-display text-2xl">{a}</h3><p className="mt-3 muted">{b}</p></div>)}</div></section>
    <section id="pricing" className="section !pt-0 scroll-mt-24"><div className="paper-card grid gap-6 p-6 md:grid-cols-2 mobile-stack"><div><p className="label">Free beta</p><h2 className="mt-3 font-display text-4xl">Free Beta now. Pro Waitlist for future workflow tools.</h2><p className="mt-4 muted">Use the free beta first. If you want full reminder sequences, saved clients, history, brand voice, and higher limits, join the Pro Waitlist.</p></div><div id="waitlist" className="grid scroll-mt-24 gap-3"><div className="rounded-xl border border-[var(--border)] bg-white p-4"><h3 className="font-display text-2xl">Anonymous Free</h3><p className="mt-2 muted">Situation-aware stage recommendation, one recommended email, short DM, copy buttons, and limited refinements.</p></div><div className="rounded-xl border border-[var(--border)] bg-white p-4"><h3 className="font-display text-2xl">Pro Waitlist</h3><p className="mt-2 muted">Future full reminder sequences, saved clients, reminder history, brand voice, and more freelancer email tools. No payment required.</p></div></div></div></section>
    <section id="faq" className="section !pt-0 scroll-mt-24"><h2 className="font-display text-4xl">FAQ</h2><div className="mt-6 grid gap-3">{faqs.map(([q,a])=><details className="paper-card p-5" key={q}><summary className="cursor-pointer font-semibold">{q}</summary><p className="mt-3 muted">{a}</p></details>)}</div></section>
    <section className="section !pt-0 text-center"><h2 className="font-display text-4xl">Stop guessing how firm your payment reminder should be.</h2><p className="mx-auto mt-4 max-w-2xl muted">Describe the situation, get the recommended reminder stage, review the draft, and send it yourself when it feels right.</p><div className="mt-6 flex flex-col justify-center gap-3 sm:flex-row"><Link className="btn btn-primary" href={routes.tool}>Start a reminder</Link><Link className="btn btn-secondary" href="#tool-entry">Use the free beta</Link></div></section>
  </>;
}
